spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/expense
spring.datasource.username=root
spring.datasource.password=MARLBORO@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This lets Spring create the tables for you automatically!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
